---
- hosts: appserver
  become : true
  tasks:

  - name: Remove current war file /usr/local/tomcat/webapps/devops.war
    file: path=/usr/local/tomcat/webapps/devops.war state=absent

  - name: Wait until the webapp folder /usr/local/tomcat/webapps/devops is deleted
    wait_for:
      path: /usr/local/tomcat/webapps/devops
      state: absent

  - name: Copy the war file ROOT.war as devops.war.tmp to /usr/local/tomcat/webapps/
    copy:
      src: /var/lib/jenkins/workspace/Project-DevOps/target/devops-1.war
      dest: /usr/local/tomcat/webapps/devops.war
      force: yes
