---
- hosts: appserver
  sudo: yes
  tasks:

  - name: Copy the war file ROOT.war as Webstore.war.tmp to /usr/local/tomcat/webapps/
    copy:
      src: /var/lib/jenkins/workspace/ProjectDemo/target/*.war
      dest: /usr/local/tomcat/webapps/Webstore.war.20191207
      force: yes

  - name: Remove current war file /usr/local/tomcat/webapps/Webstore.war
    file: path=/usr/local/tomcat/webapps/Webstore.war state=absent

  - name: Wait until the webapp folder /usr/local/tomcat/webapps/Webstore is deleted
    wait_for:
      path: /usr/local/tomcat/webapps/Webstore
      state: absent

  - name: rename the /usr/local/tomcat/webapps/Webstore.war.tmp to /usr/local/tomcat/webapps/Webstore.war
    command: "mv /usr/local/tomcat/webapps/Webstore.war.tmp /usr/local/tomcat/webapps/Webstore.war"
